version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  memcached:
    image: memcached
    networks:
    - back
  db:
    image: mysql
    volumes:
      - /dev/log:/dev/log
      - ./data/mysql/runtime:/var/lib/mysql
      - ./data/mysql/dump:/dump
    env_file:
      - ./env
    environment:
      MYSQL_DATABASE: vimbadmin
      MYSQL_USER: vimbadmin
    networks:
    - back
  spamassassin:
      image: indiehosters/spamassassin
      links:
        - dovecot
      volumes:
        - /dev/log:/dev/log
    networks:
    - back
  postfix:
    image: indiehosters/postfix
    hostname: "$VIRTUAL_HOST"
    links:
      - db
      - spamassassin
      - dovecot
    volumes: 
      - ./opendkim:/etc/opendkim
      - ./TLS:/ssl 
      - /dev/log:/dev/log
      - ./tmp:/var/spool/postfix
    ports:
      - "25:25"
      - "587:587"
    networks:
    - back
  dovecot:
    image: indiehosters/dovecot
    links:
      - db
    volumes:
      - ./data/dovecot/mail:/mail
      - ./TLS:/ssl
      - /dev/log:/dev/log
    ports:
      - "993:993"
      - "995:995"
    networks:
    - back
  vimbadmin:
    image: indiehosters/vimbadmin
    hostname: "$VIRTUAL_HOST"
    links:
      - db
      - memcached
      - postfix
    volumes_from:
      - dovecot 
    volumes:
      - ./salts:/salts
      - ./indie.signed.mobileconfig:/var/www/html/public/indie.signed.mobileconfig
      - ./email_template:/var/www/html/application/views/mailbox/email/settings.phtml
    env_file:
      - ./env
    environment:
      - APPLICATION_ENV=production
      - CLOUD_HOST
    networks:
    - back
  web:
    image: nginx
    hostname: "$VIRTUAL_HOST"
    links:
      - vimbadmin
    volumes_from:
      - vimbadmin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST
      - AUTOCONFIG_HOST="$VIRTUAL_HOST"
    networks:
    - back
    - lb_web
